---
title: S2017T5a
max_points: 1
instructions: |
view_type: access.types.stdasync.acceptPost 
fields: # näiden täytyy olla valideja HTML-formien attribuutteja
  - name: ratkaisu # Lomakkeen nimi verkkosivulla
    title: Ratkaisu # Näkyy syötekentän yläpuolella
    required: True

# configuration for the new Docker container grading sandbox
container:
  image: sesodesa/grade-mathcheck:2019-04-22
  mount: exercises/mathcheck-example
  cmd: /exercise/run.sh
